import "../globals.css";
import Footer from "@/components/common/footer/Footer";
import MainContextProvider from "./MainContextProvider";
import HoverEffectNavbar from "@/components/common/HoverEffectNavbar";
// import { Toaster } from "react-hot-toast";
import Providers from "@/components/providers/TanstackProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <MainContextProvider>
        <HoverEffectNavbar />
        {children}
        <Footer></Footer>
      </MainContextProvider>
      {/* <Toaster /> */}
    </Providers>
  );
}
