import "./globals.css";
import { Inter } from "next/font/google";
import ReduxProvider from "../../provider/redux/ReduxProvider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={inter.className}>
          {children}
          <Toaster />
        </body>
      </html>
    </ReduxProvider>
  );
};

export default RootLayout;
